services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - grades-service

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  grades-service:
    build: ./grades-service
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-school
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schooldb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql